INSERT INTO ZOOLOGICOS (NOMBRE,CIUDAD,PAIS,AREA,PRESUPUESTO) VALUES('ZOOLOGICO A','CIUDAD A','PAIS A',20000,5000000);
INSERT INTO ZOOLOGICOS (NOMBRE,CIUDAD,PAIS,AREA,PRESUPUESTO) VALUES('ZOOLOGICO B','CIUDAD B','PAIS B',10000,2000000);
INSERT INTO ZOOLOGICOS (NOMBRE,CIUDAD,PAIS,AREA,PRESUPUESTO) VALUES('ZOOLOGICO C','CIUDAD C','PAIS C',60000,9000000);
INSERT INTO ZOOLOGICOS (NOMBRE,CIUDAD,PAIS,AREA,PRESUPUESTO) VALUES('ZOOLOGICO D','CIUDAD D','PAIS D',20000,3000000);

INSERT INTO ESPECIES (NOMBRE_ESPECIE,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,EXTINCION) VALUES('TIGRE','TIGRE COMUN','PANTERA TIGRIS','FELIDAE','SI')
INSERT INTO ESPECIES (NOMBRE_ESPECIE,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,EXTINCION) VALUES('JIRAFA','JIRAFA COMUN','GIRAFA CAMELOPARDALIS','GIRAFFIDE','NO')
INSERT INTO ESPECIES (NOMBRE_ESPECIE,NOMBRE_VULGAR,NOMBRE_CIENTIFICO,FAMILIA,EXTINCION) VALUES('ELEFANTE','ELEFANTE ASIATICO','ELEFANTE MAXIMUS','ELEPHANTIDAE','SI')

INSERT INTO ANIMALES (ZOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE)  VALUES(1,1,'MACHO','2010-10-25','INDIA','ASIA')
INSERT INTO ANIMALES (ZOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE)  VALUES(1,2,'HEMBRA','2005-01-15','SUDAFRICA','AFRICA')
INSERT INTO ANIMALES (ZOLOGICO_ID,ESPECIE_ID,SEXO,FECHA_NACIMIENTO,PAIS,CONTINENTE)  VALUES(1,3,'ELEFANTE','2010-10-25','TAILANDIA','ASIA')

