INSERT INTO INMUEBLE (DIRECCION,CIUDAD,PAIS,ZONA,LLAVES,AREA,CATEGORIA,ESTADO) VALUES ('CARRERA 13', 'BUCARAMANGA','COLOMBIA','ORINOCO',1,10.5,'LOCAL','ARRENDADO');
INSERT INTO INMUEBLE (DIRECCION, CIUDAD, PAIS, ZONA, LLAVES, AREA, CATEGORIA, ESTADO) VALUES ('CALLE 45', 'MEDELLIN', 'COLOMBIA', 'EL POBLADO', 0, 20.0, 'OFICINA', 'DISPONIBLE');
INSERT INTO INMUEBLE (DIRECCION, CIUDAD, PAIS, ZONA, LLAVES, AREA, CATEGORIA, ESTADO) VALUES ('AVENIDA CENTRAL', 'BARRANQUILLA', 'COLOMBIA', 'CENTRO', 1, 25.0, 'LOCAL', 'ARRENDADO');
INSERT INTO INMUEBLE (DIRECCION, CIUDAD, PAIS, ZONA, LLAVES, AREA, CATEGORIA, ESTADO) VALUES ('CARRERA 22', 'CARTAGENA', 'COLOMBIA', 'BOCAGRANDE', 0, 18.5, 'APARTAMENTO', 'DISPONIBLE');


