INSERT INTO CLIENTES (CEDULA,NOMBRE,TELEFONO) VALUES ('1005109560','LUIGI ESTEVEZ', '3044225648')


INSERT INTO CIUDAD (NOMBRE,DETALLES) VALUES ('Bucarayork','La ciudad de los parques')

INSERT INTO OFICINA (NOMBRE,UBICACION,PHONE) VALUES ('OFICINA NORTE','Avenida quebradaseca', '304152324')


INSERT INTO INMUEBLE (REFERENCIA,SUPERFICIE,DIRECCION,PRECIO,TIPO,PROPIETARIO,LLAVES,oficina_id,ciudad_id) VALUES ('A34FCC12','300 m2', 'carrera 24 #10-43', '300000','Local','Alberto Merio','3',1,1)

INSERT INTO VISITAS (FECHA,HORA,COMENTARIO,cliente_id,inmueble_id) VALUES ('4 DE MARZO','4:00 PM', 'Cliente en busca de arriendo',1,1)
